/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\Users\\eLicht\\Documents\\kaibang\\apps\\js-book\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\Users\\eLicht\\Documents\\kaibang\\apps\\js-book\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1
]