/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "云上舟",
  "description": "个人学习博客",
  "base": "/learn-javascript/",
  "headTags": [],
  "pages": [
    {
      "title": "主题",
      "frontmatter": {
        "title": "主题",
        "author": "云上",
        "date": "2022-03-14"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-66c5182d",
      "path": "/"
    },
    {
      "title": "记忆函数",
      "frontmatter": {
        "title": "记忆函数",
        "author": "云上舟",
        "date": "2022-03-18"
      },
      "regularPath": "/book/Memorize.html",
      "relativePath": "book/Memorize.md",
      "key": "v-20d9528a",
      "path": "/book/Memorize.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是记忆函数？",
          "slug": "什么是记忆函数"
        },
        {
          "level": 2,
          "title": "记忆函数使用在哪些场景?",
          "slug": "记忆函数使用在哪些场景"
        },
        {
          "level": 2,
          "title": "记忆函数的原理",
          "slug": "记忆函数的原理"
        },
        {
          "level": 2,
          "title": "记忆函数的实现",
          "slug": "记忆函数的实现"
        },
        {
          "level": 2,
          "title": "函数测试",
          "slug": "函数测试"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Node安装及版本控制",
      "frontmatter": {
        "title": "Node安装及版本控制",
        "author": "云上舟",
        "date": "2022-03-22"
      },
      "regularPath": "/book/Node%E5%8D%B8%E8%BD%BD%E3%80%81%E5%AE%89%E8%A3%85%E5%8F%8A%E7%89%88%E6%9C%AC%E5%88%87%E6%8D%A2.html",
      "relativePath": "book/Node卸载、安装及版本切换.md",
      "key": "v-35a36269",
      "path": "/book/Node%E5%8D%B8%E8%BD%BD%E3%80%81%E5%AE%89%E8%A3%85%E5%8F%8A%E7%89%88%E6%9C%AC%E5%88%87%E6%8D%A2.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book/Vue3%E7%9A%84%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95.html",
      "relativePath": "book/Vue3的基本用法.md",
      "key": "v-0ee41b2c",
      "path": "/book/Vue3%E7%9A%84%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book/Vuex%E7%9A%84%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95.html",
      "relativePath": "book/Vuex的基本用法.md",
      "key": "v-3808a534",
      "path": "/book/Vuex%E7%9A%84%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/book/Vue%E5%BA%94%E6%9C%89%E7%9A%84%E6%9E%B6%E6%9E%84.html",
      "relativePath": "book/Vue应有的架构.md",
      "key": "v-3111fc3e",
      "path": "/book/Vue%E5%BA%94%E6%9C%89%E7%9A%84%E6%9E%B6%E6%9E%84.html"
    },
    {
      "title": "事件循环",
      "frontmatter": {
        "title": "事件循环",
        "author": "云上舟",
        "date": "2022-03-24"
      },
      "regularPath": "/book/%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.html",
      "relativePath": "book/事件循环.md",
      "key": "v-29c6e265",
      "path": "/book/%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.html",
      "headers": [
        {
          "level": 2,
          "title": "事件循环的定义",
          "slug": "事件循环的定义"
        },
        {
          "level": 2,
          "title": "浏览器任务的分类",
          "slug": "浏览器任务的分类"
        },
        {
          "level": 2,
          "title": "浏览器事件循环执行机制",
          "slug": "浏览器事件循环执行机制"
        },
        {
          "level": 2,
          "title": "例题",
          "slug": "例题"
        },
        {
          "level": 3,
          "title": "题1",
          "slug": "题1"
        },
        {
          "level": 3,
          "title": "题2",
          "slug": "题2"
        },
        {
          "level": 2,
          "title": "问题的萌生与解决",
          "slug": "问题的萌生与解决"
        },
        {
          "level": 3,
          "title": "示例1,所有async不带有异步返回值。",
          "slug": "示例1-所有async不带有异步返回值。"
        },
        {
          "level": 3,
          "title": "示例2,所有async带有异步返回值。",
          "slug": "示例2-所有async带有异步返回值。"
        },
        {
          "level": 2,
          "title": "Node中的事件循环",
          "slug": "node中的事件循环"
        },
        {
          "level": 3,
          "title": "node任务的分类",
          "slug": "node任务的分类"
        },
        {
          "level": 3,
          "title": "Process.nextTick",
          "slug": "process-nexttick"
        },
        {
          "level": 3,
          "title": "node事件循环执行机制",
          "slug": "node事件循环执行机制"
        },
        {
          "level": 2,
          "title": "node和浏览器eventLoop的主要区别",
          "slug": "node和浏览器eventloop的主要区别"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "柯里化",
      "frontmatter": {
        "title": "柯里化",
        "author": "云上舟",
        "date": "2022-03-28"
      },
      "regularPath": "/book/%E6%9F%AF%E9%87%8C%E5%8C%96.html",
      "relativePath": "book/柯里化.md",
      "key": "v-ef80196c",
      "path": "/book/%E6%9F%AF%E9%87%8C%E5%8C%96.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是柯里化？",
          "slug": "什么是柯里化"
        },
        {
          "level": 2,
          "title": "使用场景",
          "slug": "使用场景"
        },
        {
          "level": 2,
          "title": "经典例子",
          "slug": "经典例子"
        },
        {
          "level": 2,
          "title": "进阶",
          "slug": "进阶"
        },
        {
          "level": 3,
          "title": "逻辑上分为几个步骤",
          "slug": "逻辑上分为几个步骤"
        },
        {
          "level": 3,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 2,
          "title": "经典面试题",
          "slug": "经典面试题"
        },
        {
          "level": 3,
          "title": "隐式转换解释",
          "slug": "隐式转换解释"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    },
    {
      "title": "序言",
      "frontmatter": {
        "title": "序言",
        "author": "云上舟",
        "date": "2022-03-14"
      },
      "regularPath": "/home/home.html",
      "relativePath": "home/home.md",
      "key": "v-7a55579b",
      "path": "/home/home.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        }
      ]
    },
    {
      "title": "Es6数组测试",
      "frontmatter": {
        "title": "Es6数组测试",
        "author": "云上舟",
        "date": "2022-03-16"
      },
      "regularPath": "/homework/Es6%E6%95%B0%E7%BB%84API%E7%BB%83%E4%B9%A0.html",
      "relativePath": "homework/Es6数组API练习.md",
      "key": "v-7a516b16",
      "path": "/homework/Es6%E6%95%B0%E7%BB%84API%E7%BB%83%E4%B9%A0.html",
      "headers": [
        {
          "level": 3,
          "title": "测试内容",
          "slug": "测试内容"
        },
        {
          "level": 3,
          "title": "题目详解",
          "slug": "题目详解"
        }
      ]
    },
    {
      "title": "闭包",
      "frontmatter": {
        "title": "闭包",
        "author": "云上舟",
        "date": "2022-03-25"
      },
      "regularPath": "/book/%E9%97%AD%E5%8C%85.html",
      "relativePath": "book/闭包.md",
      "key": "v-ea167bec",
      "path": "/book/%E9%97%AD%E5%8C%85.html",
      "headers": [
        {
          "level": 2,
          "title": "闭包的定义",
          "slug": "闭包的定义"
        },
        {
          "level": 2,
          "title": "闭包的作用（使用场景）",
          "slug": "闭包的作用-使用场景"
        },
        {
          "level": 2,
          "title": "闭包的性质",
          "slug": "闭包的性质"
        },
        {
          "level": 2,
          "title": "闭包引发的问题",
          "slug": "闭包引发的问题"
        },
        {
          "level": 2,
          "title": "手写闭包",
          "slug": "手写闭包"
        }
      ]
    },
    {
      "title": "提升代码健壮性",
      "frontmatter": {
        "title": "提升代码健壮性",
        "author": "云上舟",
        "date": "2022-03-24"
      },
      "regularPath": "/book/%E6%8F%90%E9%AB%98%E4%BB%A3%E7%A0%81%E5%81%A5%E5%A3%AE%E6%80%A7.html",
      "relativePath": "book/提高代码健壮性.md",
      "key": "v-1edfbf31",
      "path": "/book/%E6%8F%90%E9%AB%98%E4%BB%A3%E7%A0%81%E5%81%A5%E5%A3%AE%E6%80%A7.html",
      "headers": [
        {
          "level": 2,
          "title": "更安全地访问数据",
          "slug": "更安全地访问数据"
        },
        {
          "level": 2,
          "title": "空值合并运算符",
          "slug": "空值合并运算符"
        },
        {
          "level": 3,
          "title": "封装一个安全获取对象属性API",
          "slug": "封装一个安全获取对象属性api"
        },
        {
          "level": 2,
          "title": "更稳定的第三方模块",
          "slug": "更稳定的第三方模块"
        },
        {
          "level": 3,
          "title": "设备适配例子",
          "slug": "设备适配例子"
        },
        {
          "level": 3,
          "title": "模块导入的副作用",
          "slug": "模块导入的副作用"
        },
        {
          "level": 2,
          "title": "在本地配置文件",
          "slug": "在本地配置文件"
        },
        {
          "level": 2,
          "title": "Code Review",
          "slug": "code-review"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "事件委托",
      "frontmatter": {
        "title": "事件委托",
        "author": "云上舟",
        "date": "2022-03-21"
      },
      "regularPath": "/homework/%E4%BA%8B%E4%BB%B6%E5%A7%94%E6%89%98.html",
      "relativePath": "homework/事件委托.md",
      "key": "v-3ccca467",
      "path": "/homework/%E4%BA%8B%E4%BB%B6%E5%A7%94%E6%89%98.html",
      "headers": [
        {
          "level": 2,
          "title": "测试内容",
          "slug": "测试内容"
        },
        {
          "level": 2,
          "title": "题目详解",
          "slug": "题目详解"
        }
      ]
    },
    {
      "title": "ES6面试题",
      "frontmatter": {
        "title": "ES6面试题",
        "author": "云上舟",
        "date": "2022-03-20"
      },
      "regularPath": "/homework/ES6%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "homework/ES6面试题.md",
      "key": "v-39a86269",
      "path": "/homework/ES6%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "说明数组中 map 和 forEach 的区别？",
          "slug": "说明数组中-map-和-foreach-的区别"
        },
        {
          "level": 2,
          "title": "数组的 find 中，如果有两个以上条件满足，则返回?",
          "slug": "数组的-find-中-如果有两个以上条件满足-则返回"
        },
        {
          "level": 2,
          "title": "解释说明 js 的深拷贝和浅拷贝的区别",
          "slug": "解释说明-js-的深拷贝和浅拷贝的区别"
        },
        {
          "level": 3,
          "title": "什么是浅拷贝？",
          "slug": "什么是浅拷贝"
        },
        {
          "level": 3,
          "title": "什么是深拷贝？",
          "slug": "什么是深拷贝"
        },
        {
          "level": 3,
          "title": "两者的区别",
          "slug": "两者的区别"
        },
        {
          "level": 3,
          "title": "浅拷贝举例",
          "slug": "浅拷贝举例"
        },
        {
          "level": 3,
          "title": "深拷贝举例",
          "slug": "深拷贝举例"
        },
        {
          "level": 3,
          "title": "浅拷贝的方法有哪些？",
          "slug": "浅拷贝的方法有哪些"
        },
        {
          "level": 3,
          "title": "深拷贝的实现方式有哪些？",
          "slug": "深拷贝的实现方式有哪些"
        },
        {
          "level": 2,
          "title": "说明 es6 中箭头函数的特点和作用",
          "slug": "说明-es6-中箭头函数的特点和作用"
        },
        {
          "level": 2,
          "title": "说明所有 js 类型转换成的布尔值是?",
          "slug": "说明所有-js-类型转换成的布尔值是"
        },
        {
          "level": 2,
          "title": "解释说明什么是递归，并且手写一个递归函数出来",
          "slug": "解释说明什么是递归-并且手写一个递归函数出来"
        },
        {
          "level": 2,
          "title": "解释说明函数节流和函数防抖，并且分别手写出来。",
          "slug": "解释说明函数节流和函数防抖-并且分别手写出来。"
        },
        {
          "level": 3,
          "title": "什么是防抖？",
          "slug": "什么是防抖"
        },
        {
          "level": 3,
          "title": "什么是节流",
          "slug": "什么是节流"
        },
        {
          "level": 2,
          "title": "编程题",
          "slug": "编程题"
        },
        {
          "level": 3,
          "title": "写一个 getColor 函数，返回随机十六进制颜色",
          "slug": "写一个-getcolor-函数-返回随机十六进制颜色"
        }
      ]
    },
    {
      "title": "阅读前言",
      "frontmatter": {
        "title": "阅读前言",
        "author": "云上舟",
        "date": "2022-03-14"
      },
      "regularPath": "/homework/%E5%89%8D%E8%A8%80.html",
      "relativePath": "homework/前言.md",
      "key": "v-7c459475",
      "path": "/homework/%E5%89%8D%E8%A8%80.html"
    },
    {
      "title": "数据过滤(末版)",
      "frontmatter": {
        "title": "数据过滤(末版)",
        "author": "云上舟",
        "date": "2022-03-17"
      },
      "regularPath": "/homework/%E6%97%A5%E6%9C%9F%E8%BF%87%E6%BB%A4.html",
      "relativePath": "homework/日期过滤.md",
      "key": "v-2a6d7162",
      "path": "/homework/%E6%97%A5%E6%9C%9F%E8%BF%87%E6%BB%A4.html",
      "headers": [
        {
          "level": 3,
          "title": "测试内容",
          "slug": "测试内容"
        },
        {
          "level": 3,
          "title": "题目详解",
          "slug": "题目详解"
        }
      ]
    },
    {
      "title": "JS中的数据类型",
      "frontmatter": {
        "title": "JS中的数据类型",
        "author": "云上舟",
        "date": "2022-3-16"
      },
      "regularPath": "/note/DataType.html",
      "relativePath": "note/DataType.md",
      "key": "v-7289064a",
      "path": "/note/DataType.html"
    },
    {
      "title": "ES6之变量声明",
      "frontmatter": {
        "title": "ES6之变量声明",
        "author": "云上舟",
        "date": "2022-03-19"
      },
      "regularPath": "/note/ES6%E4%B9%8B%E5%8F%98%E9%87%8F%E5%A3%B0%E6%98%8E.html",
      "relativePath": "note/ES6之变量声明.md",
      "key": "v-2b1165ff",
      "path": "/note/ES6%E4%B9%8B%E5%8F%98%E9%87%8F%E5%A3%B0%E6%98%8E.html",
      "headers": [
        {
          "level": 2,
          "title": "let的用法及注意点",
          "slug": "let的用法及注意点"
        },
        {
          "level": 2,
          "title": "const的用法及注意点",
          "slug": "const的用法及注意点"
        }
      ]
    },
    {
      "title": "解构赋值",
      "frontmatter": {
        "title": "解构赋值",
        "author": "云上舟",
        "date": "2022-03-21"
      },
      "regularPath": "/note/ES6%E4%B9%8B%E8%A7%A3%E6%9E%84%E8%B5%8B%E5%80%BC.html",
      "relativePath": "note/ES6之解构赋值.md",
      "key": "v-17a09630",
      "path": "/note/ES6%E4%B9%8B%E8%A7%A3%E6%9E%84%E8%B5%8B%E5%80%BC.html",
      "headers": [
        {
          "level": 2,
          "title": "数组的解构赋值",
          "slug": "数组的解构赋值"
        },
        {
          "level": 2,
          "title": "对象的解构赋值",
          "slug": "对象的解构赋值"
        },
        {
          "level": 2,
          "title": "字符串的解构赋值",
          "slug": "字符串的解构赋值"
        },
        {
          "level": 2,
          "title": "数值和布尔值的解构赋值",
          "slug": "数值和布尔值的解构赋值"
        },
        {
          "level": 2,
          "title": "函数参数的解构赋值",
          "slug": "函数参数的解构赋值"
        },
        {
          "level": 2,
          "title": "不能使用圆括号的情况",
          "slug": "不能使用圆括号的情况"
        },
        {
          "level": 2,
          "title": "可以使用圆括号的情况",
          "slug": "可以使用圆括号的情况"
        },
        {
          "level": 2,
          "title": "用途",
          "slug": "用途"
        }
      ]
    },
    {
      "title": "typeof判断",
      "frontmatter": {
        "title": "typeof判断",
        "author": "云上",
        "date": "2022-03-15"
      },
      "regularPath": "/note/Typeof.html",
      "relativePath": "note/Typeof.md",
      "key": "v-3ac9f73b",
      "path": "/note/Typeof.html",
      "headers": [
        {
          "level": 3,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 3,
          "title": "typeof的通常用途",
          "slug": "typeof的通常用途"
        },
        {
          "level": 3,
          "title": "typeof的缺陷",
          "slug": "typeof的缺陷"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Vue3基本使用",
      "frontmatter": {
        "title": "Vue3基本使用",
        "author": "云上舟",
        "date": "2022-03-22"
      },
      "regularPath": "/note/Vue3%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.html",
      "relativePath": "note/Vue3基本使用.md",
      "key": "v-077ad31c",
      "path": "/note/Vue3%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "部分用法记录",
          "slug": "部分用法记录"
        },
        {
          "level": 3,
          "title": "组合式组件",
          "slug": "组合式组件"
        },
        {
          "level": 2,
          "title": "父子组件传值",
          "slug": "父子组件传值"
        },
        {
          "level": 3,
          "title": "父传子",
          "slug": "父传子"
        },
        {
          "level": 2,
          "title": "子传父",
          "slug": "子传父"
        },
        {
          "level": 2,
          "title": "插槽用法",
          "slug": "插槽用法"
        }
      ]
    },
    {
      "title": "reducer的各类用法",
      "frontmatter": {
        "title": "reducer的各类用法",
        "author": "云上舟",
        "date": "2022-03-20"
      },
      "regularPath": "/note/reducer%E7%9A%84%E5%A6%99%E7%94%A8.html",
      "relativePath": "note/reducer的妙用.md",
      "key": "v-2ce893a0",
      "path": "/note/reducer%E7%9A%84%E5%A6%99%E7%94%A8.html"
    },
    {
      "title": "租房信息记录",
      "frontmatter": {
        "title": "租房信息记录",
        "author": "云上舟",
        "date": "2022-03-20"
      },
      "regularPath": "/zufang/zufang.html",
      "relativePath": "zufang/zufang.md",
      "key": "v-297c225b",
      "path": "/zufang/zufang.html"
    },
    {
      "title": "Vue中的防抖",
      "frontmatter": {
        "title": "Vue中的防抖",
        "author": "云上舟",
        "date": "2022-03-27"
      },
      "regularPath": "/note/vue%E4%B8%AD%E7%9A%84%E9%98%B2%E6%8A%96.html",
      "relativePath": "note/vue中的防抖.md",
      "key": "v-75c7b910",
      "path": "/note/vue%E4%B8%AD%E7%9A%84%E9%98%B2%E6%8A%96.html",
      "headers": [
        {
          "level": 2,
          "title": "问题萌生",
          "slug": "问题萌生"
        },
        {
          "level": 2,
          "title": "解决方案",
          "slug": "解决方案"
        },
        {
          "level": 2,
          "title": "重温防抖",
          "slug": "重温防抖"
        },
        {
          "level": 2,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 3,
          "title": "报错原因",
          "slug": "报错原因"
        },
        {
          "level": 2,
          "title": "解决方法",
          "slug": "解决方法"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/home/home"
      },
      {
        "text": "其他博客",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/YunShangZhou"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "序言",
        "path": "/home/home"
      },
      {
        "title": "博客",
        "path": "/book/Memorize",
        "collapsable": false,
        "children": [
          {
            "title": "记忆函数",
            "path": "/book/Memorize"
          },
          {
            "title": "事件循环",
            "path": "/book/事件循环.md"
          },
          {
            "title": "闭包",
            "path": "/book/闭包.md"
          },
          {
            "title": "柯里化",
            "path": "/book/柯里化.md"
          },
          {
            "title": "提高代码健壮性",
            "path": "/book/提高代码健壮性.md"
          }
        ]
      },
      {
        "title": "想法/笔记",
        "path": "/note/ES6之变量声明",
        "collapsable": false,
        "children": [
          {
            "title": "ES6之变量声明",
            "path": "/note/ES6之变量声明.md"
          },
          {
            "title": "ES6之解构赋值",
            "path": "/note/ES6之解构赋值.md"
          },
          {
            "title": "Vue3基本使用",
            "path": "/note/Vue3基本使用.md"
          },
          {
            "title": "vue中的防抖",
            "path": "/note/vue中的防抖.md"
          }
        ]
      },
      {
        "title": "日常练习",
        "path": "/homework/Notice",
        "collapsable": false,
        "children": [
          {
            "title": "前言",
            "path": "/homework/前言"
          },
          {
            "title": "ES6数组测试",
            "path": "/homework/Es6数组API练习"
          },
          {
            "title": "数组过滤",
            "path": "/homework/数组过滤"
          },
          {
            "title": "ES6面试题",
            "path": "/homework/ES6面试题"
          },
          {
            "title": "事件委托",
            "path": "/homework/事件委托"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}